name = "ElastixRegistration"
uuid = "bdfa9bcb-ee50-4581-afe0-d6011255d868"
authors = ["Donghoon Lee"]
version = "1.0.0-DEV"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"

[compat]
DataFrames = "1.7.0"
DelimitedFiles = "1.9.1"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
